import { requireHotelContext, MANAGE_ROLES } from '@/lib/auth'

export default async function Verification(){
  const{admin,hotel}=await requireHotelContext(MANAGE_ROLES)
  const{data:files,error}=await admin.from('hotel_verification_files').select('id,document_type,mime_type,size_bytes,created_at').eq('hotel_id',hotel.id).order('created_at',{ascending:false})
  if(error)throw error
  return <><div className="topline"><div><span className="eyebrow">Network onboarding</span><h1>Property verification</h1></div><span className="badge">{hotel.verification_status}</span></div>
  <section className="card simpleForm"><div className="notice">Upload only documents needed to verify the legal entity, hotel/property operation, or the applicant's authority. Do not upload guest records, staff identity documents, payment-card data, or unrelated personal information.</div><form action="/api/verification" method="post" encType="multipart/form-data"><label>Document type<select name="documentType"><option value="registration">Company / entity registration</option><option value="business_license">Business / hotel license</option><option value="property_authority">Property authority / management proof</option><option value="other">Other verification document</option></select></label><label>Document<input name="document" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/jpeg,image/png,image/webp" required/><small>PDF or image, maximum 10 MB.</small></label><button className="primary">Upload private verification document</button></form></section>
  <section className="card panel section"><h2>Submitted documents</h2>{!files?.length?<p className="empty">No documents submitted yet.</p>:<table className="table"><thead><tr><th>Type</th><th>Uploaded</th><th>Size</th><th></th></tr></thead><tbody>{files.map((f:any)=><tr key={f.id}><td>{f.document_type.replaceAll('_',' ')}</td><td>{new Date(f.created_at).toLocaleString()}</td><td>{Math.ceil(Number(f.size_bytes)/1024)} KB</td><td className="actions"><a className="secondary" href={`/api/verification/${f.id}`}>Download</a><form action="/api/verification" method="post"><input type="hidden" name="action" value="remove"/><input type="hidden" name="fileId" value={f.id}/><button className="dangerBtn">Remove</button></form></td></tr>)}</tbody></table>}</section></>
}
