import { requireHotelContext, MANAGE_ROLES } from '@/lib/auth'
import { POLICY_VERSION } from '@/lib/public-config'

export default async function Settings(){
  const {admin,hotel}=await requireHotelContext(MANAGE_ROLES)
  const {data,error}=await admin.from('hotels').select('id,name,legal_entity_name,registration_number,city,country_code,legal_contact_email,verification_status,feedback_retention_months,incident_retention_months,identity_retention_months,network_terms_version,privacy_notice_version').eq('id',hotel.id).single()
  if(error)throw error
  return <><div className="topline"><div><span className="eyebrow">Property governance</span><h1>Settings</h1></div><span className="badge">{data.verification_status}</span></div>
  <section className="card panel"><h2>Verified identity</h2><dl className="settingsFacts"><div><dt>Property</dt><dd>{data.name}</dd></div><div><dt>Legal entity</dt><dd>{data.legal_entity_name||'—'}</dd></div><div><dt>Registration</dt><dd>{data.registration_number||'—'}</dd></div><div><dt>Location</dt><dd>{data.city||'—'} · {data.country_code||'—'}</dd></div></dl></section>
  <form className="card simpleForm section" action="/api/settings" method="post"><span className="eyebrow">Privacy and retention</span><label>Legal / privacy contact email<input name="legalContactEmail" type="email" defaultValue={data.legal_contact_email} required/></label><label>Stay feedback retention review (months)<input name="feedbackRetentionMonths" type="number" min={6} max={120} defaultValue={data.feedback_retention_months} required/></label><label>Incident retention review (months)<input name="incidentRetentionMonths" type="number" min={12} max={180} defaultValue={data.incident_retention_months} required/></label><label>Guest identity retention review (months)<input name="identityRetentionMonths" type="number" min={12} max={180} defaultValue={data.identity_retention_months} required/></label><div className="notice">These values schedule human retention review; they do not automatically erase records or evidence. Set periods to the policy approved for this property and jurisdiction.</div><label className="checkLabel"><span><input name="attest" type="checkbox" required/> I confirm these settings reflect the property's current approved retention and privacy-contact policy.</span></label><button className="primary">Save governance settings</button><small>Current network terms: {data.network_terms_version||'legacy'} · current service policy version: {POLICY_VERSION}</small></form></>
}
