import { createInterface } from 'node:readline/promises'
import { stdin as input, stdout as output } from 'node:process'
import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

const rl = createInterface({ input, output })
const clean = (value='') => String(value).replace(/[\r\n]/g, '').trim()
const current = {}
if (existsSync('.env.local')) {
  for (const raw of readFileSync('.env.local','utf8').split(/\r?\n/)) {
    const line = raw.trim()
    if (!line || line.startsWith('#')) continue
    const i=line.indexOf('=')
    if(i>0) current[line.slice(0,i).trim()] = line.slice(i+1).trim()
  }
}
async function ask(label, key, fallback='') {
  const old=current[key] || fallback
  const suffix=old ? ` [${key.includes('KEY')||key.includes('SECRET')||key.includes('TOKEN') ? 'keep existing' : old}]` : ''
  const answer=clean(await rl.question(`${label}${suffix}: `))
  return answer || old
}
async function main(){
  console.log('\nGuestAtlas configuration wizard')
  console.log('This writes .env.local. High-entropy application secrets are generated automatically.\n')
  if (existsSync('.env.local')) {
    const answer=clean(await rl.question('.env.local already exists. Update it? [y/N]: ')).toLowerCase()
    if(!['y','yes'].includes(answer)){ console.log('No changes made.'); return }
  }
  const supabaseUrl=await ask('Supabase project URL','NEXT_PUBLIC_SUPABASE_URL')
  const publishable=await ask('Supabase publishable key','NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY')
  const secret=await ask('Supabase server secret key','SUPABASE_SECRET_KEY')
  const projectRef=await ask('Supabase project ref','SUPABASE_PROJECT_REF')
  const appUrl=await ask('Production app URL (for example https://guestatlas.example.com)','NEXT_PUBLIC_APP_URL','http://localhost:3000')
  const adminEmails=await ask('Bootstrap platform admin email(s), comma separated; optional','PLATFORM_ADMIN_EMAILS')
  const resend=await ask('Resend API key; optional','RESEND_API_KEY')
  const emailFrom=await ask('Invitation email sender; optional','EMAIL_FROM','GuestAtlas <noreply@example.com>')
  const supabaseToken=await ask('Supabase access token; optional (otherwise deploy prompts login)','SUPABASE_ACCESS_TOKEN')
  const vercelToken=await ask('Vercel token; optional (otherwise deploy prompts login)','VERCEL_TOKEN')

  const pii=current.PII_ENCRYPTION_KEY && current.PII_ENCRYPTION_KEY!=='REPLACE_ME' ? current.PII_ENCRYPTION_KEY : randomBytes(32).toString('base64')
  const matching=current.MATCHING_SECRET && current.MATCHING_SECRET!=='REPLACE_ME' ? current.MATCHING_SECRET : randomBytes(64).toString('hex')
  const audit=current.AUDIT_HASH_SECRET && current.AUDIT_HASH_SECRET!=='REPLACE_ME' ? current.AUDIT_HASH_SECRET : randomBytes(64).toString('hex')
  const cron=current.CRON_SECRET && current.CRON_SECRET!=='REPLACE_ME' ? current.CRON_SECRET : randomBytes(48).toString('base64url')
  const values={
    NEXT_PUBLIC_SUPABASE_URL:supabaseUrl,
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:publishable,
    SUPABASE_SECRET_KEY:secret,
    PII_ENCRYPTION_KEY:pii,
    MATCHING_SECRET:matching,
    AUDIT_HASH_SECRET:audit,
    NEXT_PUBLIC_APP_URL:appUrl.replace(/\/$/,''),
    RESEND_API_KEY:resend,
    EMAIL_FROM:emailFrom,
    PLATFORM_ADMIN_EMAILS:adminEmails,
    REQUIRE_MFA:'true',
    SUPABASE_PROJECT_REF:projectRef,
    SUPABASE_ACCESS_TOKEN:supabaseToken,
    VERCEL_TOKEN:vercelToken,
    CRON_SECRET:cron,
  }
  for(const [k,v] of Object.entries(values)) if(/[\r\n]/.test(v)) throw new Error(`${k} cannot contain a newline`)
  const text = `# Generated by configure.cmd / scripts/configure.mjs\n${Object.entries(values).map(([k,v])=>`${k}=${v}`).join('\n')}\n`
  writeFileSync('.env.local',text,{mode:0o600})
  console.log('\n.env.local written. Cryptographic application secrets were generated automatically.')
  if(values.NEXT_PUBLIC_APP_URL.startsWith('http://localhost')) console.log('WARNING: set NEXT_PUBLIC_APP_URL to the final HTTPS production origin before a real production launch.')
  console.log('Next: run deploy.cmd')
}
try{await main()}finally{rl.close()}
